disabled_rules: # rule identifiers to disabled rules
- trailing_whitespace
- line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- .build

file_length:
  warning: 1000
  error: 1200
  
force_cast: error
force_unwrapping: error
