disabled_rules: # rule identifiers to disabled rules
- trailing_whitespace
- line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- .build
- Dangerfile.swift

file_length:
  warning: 1000
  error: 1200
  
function_body_length:
  warning: 40
  error: 80
  
force_cast: error
force_unwrapping: error
