language: objective-c
osx_image: xcode13

script:
  - xcodebuild test -project SwiftlintDangerSample.xcodeproj -scheme SwiftlintDangerSample -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator13.0 CODE_SIGNING_REQUIRED=NO