name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run List Simulator
        run: xcrun simctl list
      - name: Build iOS App
        run: xcodebuild -project SwiftlintDangerSample.xcodeproj -scheme "SwiftlintDangerSample" -destination "platform=iOS Simulator,name=iPhone 11 Pro
